name: dpot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - accelerate=0.23.0
  - h5py=3.7.0
  - matplotlib=3.5.2
  - pandas=1.4.4
  - einops=0.7.0
  - timm=0.9.7
  - yaml=0.2.5
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.9.1
  - pip
  - pip:
      - tensorboard==2.14.1
      - torch-optimizer==0.3.0
